server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shinyay-api
            client-secret: 280537a8-a9ee-42db-8693-839b8707c62c
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
#            scope: read,write
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:8083/auth/realms/shinyay/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/shinyay/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8083/auth/realms/shinyay/protocol/openid-connect/certs
            user-info-uri: http://localhost:8083/auth/realms/shinyay/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
resourceserver:
  api:
    url: http://localhost:8081/resource-server/api/v1/employees
