server:
  port: 8080
keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: shinyay
  base-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: shinyay-api
            client-secret: 0c5d257f-47bf-47e7-9400-08759fade9d9
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
            provider: keycloak
          google:
            client-id: 748706999601-gf59b6pdtn2tvfujli466vue8lddtudt.apps.googleusercontent.com
            client-secret: ipHuyafsi4t3VVygH_NOldkN
        provider:
          keycloak:
            authorization-uri: ${keycloak.base-uri}/auth
            token-uri: ${keycloak.base-uri}/token
            jwk-set-uri: ${keycloak.base-uri}/certs
            user-info-uri: ${keycloak.base-uri}/userinfo
            user-name-attribute: preferred_username
  jackson:
    serialization:
      indent_output: true
resourceserver:
  api:
    url: http://localhost:8081/resource-server/api/v1/employees
